In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('train_data.txt',delimiter=' ::: ',engine='python', header = None)
print(train_data)
test_data = pd.read_csv('test_data_solution.txt', delimiter = ' ::: ', engine = 'python', header = None)

           0                                           1            2  \
0          1                Oscar et la dame rose (2009)        drama   
1          2                                Cupid (1997)     thriller   
2          3            Young, Wild and Wonderful (1980)        adult   
3          4                       The Secret Sin (1915)        drama   
4          5                      The Unrecovered (2007)        drama   
...      ...                                         ...          ...   
54209  54210                             "Bonino" (1953)       comedy   
54210  54211                 Dead Girls Don't Cry (????)       horror   
54211  54212   Ronald Goedemondt: Ze bestaan echt (2008)  documentary   
54212  54213                    Make Your Own Bed (1944)       comedy   
54213  54214  Nature's Fury: Storm of the Century (2006)      history   

                                                       3  
0      Listening in to a conversation between his doc...  
1    

In [3]:
train_data.columns = ['movie_ID','movie_name','movie_genre','movie_description']
train_data = train_data.drop(['movie_ID','movie_name'], axis = 1)
test_data.columns = ['movie_ID','movie_name','movie_genre','movie_description']
test_data = test_data.drop(['movie_ID','movie_name'], axis = 1)

In [4]:
print(test_data)

       movie_genre                                  movie_description
0         thriller  L.R. Brane loves his life - his car, his apart...
1           comedy  Spain, March 1964: Quico is a very naughty chi...
2      documentary  One year in the life of Albin and his family o...
3            drama  His father has died, he hasn't spoken with his...
4            drama  Before he was known internationally as a marti...
...            ...                                                ...
54195       horror  Covering multiple genres, Tales of Light & Dar...
54196      western  As Alice and Cora Munro attempt to find their ...
54197        adult  A movie 169 years in the making. Oliver Twist,...
54198        drama  Popular, but mysterious rock D.J Mike Mallard ...
54199        drama  Curitiba is a city in movement, with rhythms a...

[54200 rows x 2 columns]


In [5]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
def text_preprocess (text):
    text = text.lower()
    text = re.sub(r'\W',' ',text)
    tokens = nltk.word_tokenize(text)
    words = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(words)

test_data['cleaned_summary'] = test_data['movie_description'].apply(text_preprocess)
train_data['cleaned_summary'] = train_data['movie_description'].apply(text_preprocess)

In [6]:
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 5000)
x_train = tfidf.fit_transform(train_data['cleaned_summary']).toarray()
x_test = tfidf.transform(test_data['cleaned_summary']).toarray()
print(x_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
y_train = train_data['movie_genre']
#y_train = np.ravel(y_train)
y_test = test_data['movie_genre']
#y_test = np.ravel(y_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
model = LogisticRegression(max_iter = 1000)
model.fit(x_train,y_train)
y_prediction = model.predict(x_test)
report = classification_report(y_prediction,y_test)
print(report)

C:\Users\fahdf\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fahdf\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

      action       0.29      0.46      0.36       832
       adult       0.27      0.62      0.37       256
   adventure       0.18      0.57      0.27       237
   animation       0.08      0.51      0.14        79
   biography       0.00      0.00      0.00         0
      comedy       0.59      0.54      0.56      8153
       crime       0.04      0.32      0.07        62
 documentary       0.84      0.67      0.75     16443
       drama       0.77      0.55      0.64     19098
      family       0.10      0.49      0.17       164
     fantasy       0.06      0.58      0.11        33
   game-show       0.54      0.83      0.65       125
     history       0.00      0.00      0.00         0
      horror       0.58      0.65      0.61      1972
       music       0.45      0.64      0.53       517
     musical       0.02      0.24      0.03        21
     mystery       0.02      0.40      0.04        15
        news       0.06    

C:\Users\fahdf\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
